import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { FollowUpQuery } from '@/components/block/follow-up-query';

const meta = {
    title: 'UI/FollowUpQuery',
    component: FollowUpQuery,
    parameters: {
        layout: 'centered',
    },
    tags: ['autodocs'],
    argTypes: {
        query: {
            control: 'text',
            description: 'The follow-up query text to display',
        },
        onClick: {
            action: 'clicked',
            description: 'Callback when the query is clicked',
        },
    },
} as Meta<typeof FollowUpQuery>;

export default meta;
type Story = StoryObj<typeof FollowUpQuery>;

export const Default: Story = {
    args: {
        query: 'This is a follow up query generated by system?',
    },
};

export const LongQuery: Story = {
    args: {
        query: 'What are the conditions for granting anticipatory bail in domestic violence cases with strong evidence against the accused?',
    },
};

export const ShortQuery: Story = {
    args: {
        query: 'What is Section 498A IPC?',
    },
};

export const VeryLongQuery: Story = {
    args: {
        query: 'In cases involving domestic violence where there is substantial evidence against the accused including medical records, witness testimony, and documented threats, what are the legal precedents and conditions under which anticipatory bail can be granted or denied?',
    },
};

export const MultipleQueries: Story = {
    args: {
        query: 'This is a follow up query generated by system?',
    },
    render: () => (
        <div className="flex flex-col w-full max-w-2xl">
            <FollowUpQuery
                query="This is a follow up query generated by system?"
                onClick={() => console.log('Query 1 clicked')}
            />
            <FollowUpQuery
                query="What are the conditions for granting anticipatory bail in domestic violence cases?"
                onClick={() => console.log('Query 2 clicked')}
            />
            <FollowUpQuery
                query="Can anticipatory bail be cancelled after being granted?"
                onClick={() => console.log('Query 3 clicked')}
            />
            <FollowUpQuery
                query="What is the difference between regular bail and anticipatory bail in such cases?"
                onClick={() => console.log('Query 4 clicked')}
            />
        </div>
    ),
};

export const ResponsiveWrapping: Story = {
    args: {
        query: 'What are the conditions for granting anticipatory bail in domestic violence cases with strong evidence?',
    },
    render: () => (
        <div className="space-y-8">
            <div>
                <h3 className="text-sm font-semibold mb-2">Narrow Container (300px)</h3>
                <div className="w-[300px]">
                    <FollowUpQuery
                        query="What are the conditions for granting anticipatory bail in domestic violence cases with strong evidence?"
                    />
                </div>
            </div>
            <div>
                <h3 className="text-sm font-semibold mb-2">Medium Container (500px)</h3>
                <div className="w-[500px]">
                    <FollowUpQuery
                        query="What are the conditions for granting anticipatory bail in domestic violence cases with strong evidence?"
                    />
                </div>
            </div>
            <div>
                <h3 className="text-sm font-semibold mb-2">Wide Container (800px)</h3>
                <div className="w-[800px]">
                    <FollowUpQuery
                        query="What are the conditions for granting anticipatory bail in domestic violence cases with strong evidence?"
                    />
                </div>
            </div>
        </div>
    ),
};
